version: '3.9'
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    volumes:
      - ./data/kafka:/var/run/docker.sock
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      
  ms-customers:
    build: ./ms-customers
    command: "npm start"
    volumes:
      - ./ms-customers:/app
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8001:8001"
    depends_on:
      - kafka

  ms-products:
    build: ./ms-products
    command: "npm start"
    volumes:
      - ./ms-products:/app
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8002:8002"
    depends_on:
      - kafka

  ms-shopping:
    build: ./ms-shopping
    command: "npm start"
    volumes:
      - ./ms-shopping:/app
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8003:8003"
    depends_on:
      - kafka

  nginx-proxy:
    build: ./nginx
    depends_on:
      - ms-products
      - ms-shopping
      - ms-customers
      - kafka
    ports:
      - "80:80"

networks:
  ms-shopping:
    driver: bridge
