# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Continuous Integration

on:
  pull_request:
    branches: [ "master" ]

jobs:
  ci_verification:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Test Customer Service
      working-directory: ./ms-customers
      run: |
        ls -l  # Listar archivos en la carpeta actual
        cat package-lock.json  # Imprimir el contenido del archivo de bloqueo de dependencias
        npm ci
        npm test

    - name: Test Products Service
      working-directory: ./ms-products
      run: |
        ls -l  # Listar archivos en la carpeta actual
        cat package-lock.json  # Imprimir el contenido del archivo de bloqueo de dependencias
        npm ci
        npm test

    - name: Test Shopping Service
      working-directory: ./ms-shopping
      run: |
        ls -l  # Listar archivos en la carpeta actual
        cat package-lock.json  # Imprimir el contenido del archivo de bloqueo de dependencias
        npm ci
        npm test